# Configuration for GCP/Discord
GCP:
    ServiceAccountKeyPath: ""
    ProjectId: ""
    Zone: ""
    InstanceName: ""

Discord:
    Token: ""
    GCPChannelId: 
    Presence:
        Activity: ""

MySQL:
    Host: ""
    Database: ""
    Port: 
    User: ""
    Password: ""
