# FMC Configuration File
MySQL:
    Host: ""
    Database: ""
    Port: 
    User: ""
    Password: ""

Socket:
    Client_Port: 
    Server_Port: 

Discord:
    Webhook_URL: ""

MCVC:
    Mode: false
    Host: "localhost"
    EXE_Path: ""

AutoStop:
    Mode: false
    Interval: 3