# Configuration for GCP/Discord
Common:
  WebHost: ""

GCP:
  Mode: false
  ServiceAccountKeyPath: ""
  ProjectId: ""
  Zone: ""
  InstanceName: ""
  WebHost: ""
  Status:
    Period: 

NonGCP: 
  LocalIP: "localhost"
  Status:
    Period: 

Discord:
  Token: ""
  GCPChannelId: 
  Command:
    Period: 
  Presence:
    Activity:
      Default: ""
      Running: ""
      Freezing: ""
      Stopping: ""
  GCPRoleId: 
  Status:
    Period: 
    ChannelId: 
    MessageId: 

MySQL:
  Host: ""
  Database: ""
  Port: 
  User: ""
  Password: ""
