# Configuration for GCP/Discord 
GCP:
    ServiceAccountKeyPath: ""
    ProjectId: ""
    Zone: ""
    InstanceName: ""

MySQL:
    Host: ""
    Database: ""
    Port: 
    User: ""
    Password: ""

Discord:
    Webhook_URL: ""