# Configuration for GCP/Discord
GCP:
    ServiceAccountKeyPath: ""
    ProjectId: ""
    Zone: ""
    InstanceName: ""
    WebHost: ""
    Status:
        Period: 

Discord:
    Token: ""
    GCPChannelId: 
    Presence:
        Activity: ""
    GCPRoleId: 
    Status:
        Period: 
        ChannelId: 
        MessageId: 

MySQL:
    Host: ""
    Database: ""
    Port: 
    User: ""
    Password: ""
