# Configuration for GCP/Discord 
GCP:
    ServiceAccountKeyPath: ""
    ProjectId: ""
    Zone: ""
    InstanceName: ""

Discord:
    Token: ""
    ResponseUrl: ""
    GCPChannelId: 

MySQL:
    Host: ""
    Database: ""
    Port: 
    User: ""
    Password: ""
